path:
  ckpt_path: "../output/ckpt/ailabs_learned_embeds"
  log_path: "../output/log/ailabs_learned_embeds"
  result_path: "../output/result/ailabs_learned_embeds"
optimizer:
  batch_size: 4
  betas: [0.95, 0.999]
  eps: 0.00001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 8
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 5000
